### ISSUE TITLE
How to run apk with droidbox in emulator?

### ISSUE THREAD

**Issue by dinasaif** [pjlantz/droidbox#12]
Hiiiiiii,
I run droidbox in windows 7 but I use bash to write commands .
When I write :  ./startemu.sh DroidBox
the emulator runs but when I write :   ./droidbox.sh app.apk 100

The next error appear :  Traceback (most recent call last):
  File "scripts/droidbox.py", line 28, in <module>
    import sys, json, time, curses, signal, os, inspect
  File "C:\Python27\lib\curses__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
what that mean I installed python 2.7.11 version 
can you help me please in details

**Comment by dinasaif** [comment]
Santuko distribution solve the errors because it has the missing libraries
